### ISSUE TITLE
I need some help (not really an issue)

### ISSUE THREAD

**Issue by obp3ter** [RuscalWorld/FabricExporter#3]
I love your mod, but I need some help with the Grafana dashboard setup. How do I separate two Minecraft servers into different dashboards?

**Comment by RuscalWorld** [comment]
Adding multiple servers is not supported now. I'll try to add this in the near future.

**Comment by obp3ter** [comment]
Well, it would be possible to run 2 separate instances of Prometheus (and maybe also Grafana), but it's kind of a hassle, and I'm sure it can be done in Grafana, I just don't know how, because I never worked with it. I'll continue using it, It'll just take a bit more until I figure out which line is which in the graphs.

**Comment by RuscalWorld** [comment]
I've updated a Grafana dashboard so it now supports selecting servers. In order to use this, you should reimport dashboard.

> How do I separate two Minecraft servers into different dashboards?

If you want to use different dashboards, you can just import FabricExporter's dashboard twice, but it's ID and name must be changed. In this case you should have multiple instances of Prometheus, as I think. With current version of dashboard you can just hardcode values for variables in dashboard settings. Anyway, I don't see any reasons to do this, because you can use variables in a single dashboard.

**Comment by RuscalWorld** [comment]
And few words on prometheus config. It should look like this for multiple servers:

```yaml
- job_name: 'fabric'
  static_configs:
    - targets: ['127.0.0.1:25585']
    - targets: ['127.0.0.1:25586']
    - ...
```

Grafana with latest version of my dashboard doesn't require any additional configuration.

**Comment by obp3ter** [comment]
It works beautifully. Thank you.
